### PR TITLE
GET /api/v0.1/countries/random returns a random country object

### PR DESCRIPTION
**Pull request by ryzbaka**
This pull request is in response to issue : https://github.com/MartinsOnuoha/countriesNowAPI/issues/36
for returning a random country object.

image

### CODE REVIEW

**Comment by MartinsOnuoha** [comment]
@ryzbaka awesome job! now what's left is the tests and the openApi Docs.

## Open Api
For the openApi Documentation, you need to add the new endpoint to the `swagger/paths/` folder then add the endpoint and its corresponding path method in the `swagger/openApiDocumentation.js` file.

## Tests
Tests are written with Mocha & Chai.
- add a new `random.js` within the `./test` folder.
- write your assertions for the new endpoint within this file 
- import the `random.js` file into `./test/tests.js` at the bottom.


Let me know if you need any more clarification

**Review by MartinsOnuoha — CHANGES_REQUESTED** [review]
Great!, one more step, Add tests and update Swagger Docs.

**Comment by ryzbaka** [comment]
@MartinsOnuoha , sure thing; I'll get to it.

**Comment by ryzbaka** [comment]
@MartinsOnuoha , I'm new to mocha; can you verify if the following code in ./test/random.js be okay:
```javascript
/* eslint-disable no-undef */

/**
 * @module test/random
 */

const chai = require('chai');
const chaiHttp = require('chai-http');
const server = require('../app');

const basePath = '/api/v0.1/countries';
const should = chai.should();

chai.use(chaiHttp);

describe("Random",()=>{
    describe("/GET",()=>{
        it('it should get a random country object',(done)=>{
            chai.request(server)
              .get(`${basePath}/random`)
              .end((err,res)=>{
                  res.should.have.status(200);
                  should.not.exist(err);
                  res.body.should.be.a('object');
                  res.body.should.have.property('error').eql(false);
                  res.body.should.have.property('data');
                  res.body.should.have.property('msg');
                  res.body.should.have.property('data').be.a('object');
                  res.body.data.length.should.not.equal(0);
                  done();
              })
        })    
    })
})
```

**Comment by ryzbaka** [comment]
@MartinsOnuoha kindly  review the changes.

**Review by MartinsOnuoha — APPROVED** [review]
🚀 Everything looks good. Great work, I'll merge now.

**Pull request merged**
