### PR TITLE
 Created endpoint to find all cities of state #38

### LINKED ISSUE #38: add endpoint to get cities within a state.
Within the `./model/countriesStateCity.js` Files you'll find countries, their respective states, and cities within that state.

The goal is to be able to get all the cities within a state.
For example, given this data:
```
{
      "id": 1,
      "name": "Afghanistan",
      "iso3": "AFG",
      "iso2": "AF",
      "phone_code": "93",
      "capital": "Kabul",
      "currency": "AFN",
      "states": [
          {
              "id": 3901,
              "name": "Badakhshan",
              "state_code": "BDS",
              "cities": [
                  {
                      "id": 52,
                      "name": "Ashkāsham",
                      "latitude": "36.68333000",
                      "longitude": "71.53333000"
                  },
                  {
                      "id": 68,
                      "name": "Fayzabad",
                      "latitude": "37.11664000",
                      "longitude": "70.58002000"
                  },
                  {
                      "id": 78,
                      "name": "Jurm",
                      "latitude": "36.86477000",
                      "longitude": "70.83421000"
                  },
                  {
                      "id": 84,
                      "name": "Khandūd",
                      "latitude": "36.95127000",
                      "longitude": "72.31800000"
                  },
                  {
                      "id": 115,
                      "name": "Rāghistān",
                      "latitude": "37.66079000",
                      "longitude": "70.67346000"
                  },
                  {
                      "id": 131,
                      "name": "Wākhān",
                      "latitude": "37.05710000",
                      "longitude": "73.34928000"
                  }
              ]
          }
```
----------

 We need to be able to get the cities within "Badakhshan" by sending a `POST` request to the `/state/cities` endpoint with this payload: 
```json
{
   "state": "Badakhshan"
}
```

### PR DESCRIPTION
**Pull request by anuragphadnis**
- Created an endpoint post /state/cities to accept country and state in payload and return all cities of that state
- Created unit test cases for that endpoint
- Updated swagger documentation to include new endpoint

closes #38

### CODE REVIEW

**Comment by MartinsOnuoha** [comment]
@anuragphadnis Looks great, can you please make the indentations uniform, can you format the files with 2 Spaces

**Review by iambenkay — CHANGES_REQUESTED** [review]
looks clean!
Just try formatting the files with a 2 spaces indentation scheme. 
I think it's a tab now and that's too much.

**Comment by anuragphadnis** [comment]
@MartinsOnuoha @iambenkay , Did the above changes, please review

**Review by MartinsOnuoha — APPROVED** [review]
Looks good 🚀

**Comment by MartinsOnuoha** [comment]
> @MartinsOnuoha @iambenkay , Did the above changes, please review

Great job, I'll be merging into master now.

**Pull request merged**
