### PR TITLE
:bug: Country name change

### PR DESCRIPTION
**Pull request by sileski**
That country name was changed, now is just Serbia

### CODE REVIEW

**Comment by MartinsOnuoha** [comment]
Hi @sileski, thanks for the info, can you please provide a reference to this name change. The most recent reference for Serbia I have is this:
[Name change from Yugoslavia, Federal Republic of to Serbia and Montenegro](https://www.federalregister.gov/documents/2004/01/22/04-1354/name-change-of-yugoslavia-to-serbia-and-montenegro)

Can you provide a similar reference of name change from Serbia and Montenegro to Serbia?

Thanks

**Review by MartinsOnuoha — CHANGES_REQUESTED** [review]
Please provide a reference to name change

**Comment by sileski** [comment]
> Please provide a reference to name change

https://www.state.gov/independent-states-in-the-world/
https://en.wikipedia.org/wiki/History_of_Serbia#Independent_Serbia_(2006%E2%80%93present)

**Review by sileski — COMMENTED** [review]
https://www.state.gov/independent-states-in-the-world/
https://en.wikipedia.org/wiki/History_of_Serbia#Independent_Serbia_(2006%E2%80%93present)

**Comment by MartinsOnuoha** [comment]
> https://www.state.gov/independent-states-in-the-world/
> https://en.wikipedia.org/wiki/History_of_Serbia#Independent_Serbia_(2006%E2%80%93present)

Thanks, @sileski this is helpful. I'm going ahead to merge this.

**Review by MartinsOnuoha — APPROVED** [review]
Looks good

**Pull request merged**
